/*
 * Copyright (C) 2019-present Arctic Ice Studio <development@arcticicestudio.com>
 * Copyright (C) 2019-present Sven Greb <development@svengreb.de>
 *
 * Project:    Arctic
 * Repository: https://github.com/arcticicestudio/arctic
 * License:    MIT
 */

/**
 * @file Provides ambient type declarations, type shims for modules without type declarations
 * as well as asset files.
 *
 * @see https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules
 * @see https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations
 */

/**
 * Typings for React components generated by SVGR.
 *
 * @see https://www.smooth-code.com/open-source/svgr
 * @see https://github.com/zabute/gatsby-plugin-svgr#options
 * @see https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/lib/react-app.d.ts
 */
declare module "*.svg" {
  import * as React from "react";

  export const ReactComponent: React.FunctionComponent<React.SVGProps<SVGSVGElement>>;

  const src: string;
  export default src;
}
